use crate::models::{Component, Vulnerability, VexDocument, VexStatement, VexStatus};
use serde_json::{json, Value};

/// Serialize a normalised `VexDocument` into a CSAF 2.0 JSON value.
pub fn serialize(doc: &VexDocument) -> Value {
    let ts = doc.timestamp.as_deref().unwrap_or("1970-01-01T00:00:00Z");
    let author = doc.author.as_deref().unwrap_or("evidger-cli");
    let tracking_id = doc
        .id
        .as_deref()
        .unwrap_or("evidger-cli-generated");
    let version_str = doc
        .version
        .map(|v| v.to_string())
        .unwrap_or_else(|| "1".into());

    let vulnerabilities: Vec<Value> = doc
        .statements
        .iter()
        .map(serialize_statement)
        .collect();

    json!({
        "document": {
            "category": "csaf_vex",
            "csaf_version": "2.0",
            "title": doc.id.as_deref().unwrap_or("Converted VEX document"),
            "publisher": {
                "category": "vendor",
                "name": author,
                "namespace": "https://example.com"
            },
            "tracking": {
                "id": tracking_id,
                "status": "final",
                "version": version_str,
                "initial_release_date": ts,
                "current_release_date": ts,
                "revision_history": [{
                    "number": "1",
                    "date": ts,
                    "summary": "Generated by evidger-cli"
                }]
            }
        },
        "vulnerabilities": vulnerabilities
    })
}

/// Return true if `s` matches the CVE pattern `CVE-YYYY-NNNNN`.
fn is_cve_id(s: &str) -> bool {
    let Some(rest) = s.strip_prefix("CVE-") else {
        return false;
    };
    let mut parts = rest.splitn(2, '-');
    let year = parts.next().unwrap_or("");
    let num = parts.next().unwrap_or("");
    year.len() == 4
        && year.chars().all(|c| c.is_ascii_digit())
        && num.len() >= 4
        && num.chars().all(|c| c.is_ascii_digit())
}

/// Map an OpenVEX justification string to the closest CSAF flag label.
fn justification_to_csaf_label(j: &str) -> &str {
    match j {
        "component_not_present" => "component_not_present",
        "inline_mitigations_already_exist" => "inline_mitigations_already_exist",
        "vulnerable_code_cannot_be_controlled_by_adversary" => {
            "vulnerable_code_cannot_be_controlled_by_adversary"
        }
        "vulnerable_code_not_in_execute_path" => "vulnerable_code_not_in_execute_path",
        _ => "vulnerable_code_not_present",
    }
}

fn serialize_statement(stmt: &VexStatement) -> Value {
    let id = &stmt.vulnerability.id;
    let mut vuln = json!({});

    // Only set `cve` if the ID is a proper CVE identifier.
    if is_cve_id(id) {
        vuln["cve"] = Value::String(id.clone());
    } else {
        vuln["ids"] = json!([{
            "system_name": "vulnerability identifier",
            "text": id
        }]);
    }
    if let Some(d) = &stmt.vulnerability.description {
        vuln["title"] = Value::String(d.clone());
    }

    match &stmt.status {
        VexStatus::NotAffected => {
            let label = stmt
                .justification
                .as_deref()
                .map(justification_to_csaf_label)
                .unwrap_or("vulnerable_code_not_present");
            vuln["flags"] = json!([{ "label": label }]);
        }
        VexStatus::Fixed => {
            let details = stmt
                .action_statement
                .as_deref()
                .unwrap_or("Apply vendor fix");
            vuln["remediations"] = json!([{
                "category": "vendor_fix",
                "details": details
            }]);
        }
        VexStatus::Affected => {
            let details = stmt
                .action_statement
                .as_deref()
                .unwrap_or("See advisory for remediation details");
            vuln["remediations"] = json!([{
                "category": "workaround",
                "details": details
            }]);
        }
        VexStatus::UnderInvestigation => {
            vuln["notes"] = json!([{
                "category": "general",
                "text": "Under investigation",
                "title": "Status"
            }]);
        }
    }
    vuln
}

/// Parse a CSAF 2.0 document into a normalised `VexDocument`.
/// Vulnerability status is derived from `flags` (not_affected) and
/// `remediations` (fixed / affected).
pub fn parse(value: &Value) -> VexDocument {
    let doc = value.get("document").unwrap_or(&Value::Null);
    let tracking = doc.get("tracking").unwrap_or(&Value::Null);

    let id = tracking
        .get("id")
        .and_then(Value::as_str)
        .map(String::from);

    let author = doc
        .get("publisher")
        .and_then(|p| p.get("name"))
        .and_then(Value::as_str)
        .map(String::from);

    let timestamp = tracking
        .get("current_release_date")
        .and_then(Value::as_str)
        .map(String::from);

    let statements = value
        .get("vulnerabilities")
        .and_then(Value::as_array)
        .map(|arr| arr.iter().map(parse_statement).collect())
        .unwrap_or_default();

    VexDocument {
        id,
        author,
        timestamp,
        version: None,
        statements,
    }
}

fn parse_statement(v: &Value) -> VexStatement {
    let cve = v
        .get("cve")
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_string();

    let description = v
        .get("title")
        .and_then(Value::as_str)
        .map(String::from);

    let vulnerability = Vulnerability {
        id: cve,
        description,
        severity: None,
        aliases: vec![],
    };

    let flags = v.get("flags").and_then(Value::as_array);
    let remediations = v.get("remediations").and_then(Value::as_array);

    // Status mapping:
    //   flags present        → NotAffected  (justification = first flag label)
    //   remediation vendor_fix → Fixed      (action = remediation details)
    //   remediation workaround/mitigation → Affected (action = remediation details)
    //   otherwise            → UnderInvestigation
    let (status, justification, action_statement) =
        if let Some(flags) = flags.filter(|f| !f.is_empty()) {
            let just = flags[0]
                .get("label")
                .and_then(Value::as_str)
                .map(String::from);
            (VexStatus::NotAffected, just, None)
        } else if let Some(remeds) = remediations {
            if let Some(fix) = remeds
                .iter()
                .find(|r| r.get("category").and_then(Value::as_str) == Some("vendor_fix"))
            {
                let action = fix.get("details").and_then(Value::as_str).map(String::from);
                (VexStatus::Fixed, None, action)
            } else if let Some(wa) = remeds.iter().find(|r| {
                matches!(
                    r.get("category").and_then(Value::as_str),
                    Some("workaround") | Some("mitigation")
                )
            }) {
                let action = wa.get("details").and_then(Value::as_str).map(String::from);
                (VexStatus::Affected, None, action)
            } else {
                (VexStatus::UnderInvestigation, None, None)
            }
        } else {
            (VexStatus::UnderInvestigation, None, None)
        };

    // Collect affected product IDs referenced in flags or remediations
    let product_ids: Vec<String> = flags
        .into_iter()
        .flatten()
        .flat_map(|flag| {
            flag.get("product_ids")
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .map(String::from)
        })
        .collect();

    let products = product_ids
        .into_iter()
        .map(|id| Component {
            name: id.clone(),
            version: None,
            purl: None,
            bom_ref: Some(id),
        })
        .collect();

    VexStatement {
        vulnerability,
        products,
        status,
        justification,
        impact_statement: None,
        action_statement,
    }
}
